[bangs.mdn]
name = "MDN Web Docs"
url = "https://developer.mozilla.org/en-US/search?q={}"
domain = "developer.mozilla.org"

[bangs.kagi]
name = "Kagi"
url = "https://kagi.com/search?q={}"
domain = "kagi.com"

[bangs.settings]
name = "Settings"
url = "/settings"
domain = "flashbang"
